apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_HOST: "MzQuMzEuNzguMjAw"       # 34.31.78.200
  DB_NAME: "cHJvZHVjdGRi"            # productdb
  DB_USER: "cG9zdGdyZXM="            # postgres
  DB_PASS: "cG9zdGdyZXM="            # postgres (fixed!)
  DB_PORT: "NTQzMg=="                 # 5432
  API_KEY: "Y2hpbm51MzE="            # chinnu31
