apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  DB_HOST: "127.0.0.1"          # Connect via Cloud SQL Proxy
  DB_NAME: "productdb"          # Your database name
  DB_USER: "postgres"           # Your DB user
  DB_PASS: "postgres"   # Replace with real password
  DB_PORT: "5432"
  API_KEY: "chinnu31"           # Your API key
