apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_HOST: "MzQuMzEuNzguMjAw"
  DB_NAME: "cHJvZHVjdGRi"
  DB_USER: "cG9zdGdyZXM="
  DB_PASS: "cG9zdGryZXM="
  DB_PORT: "NTQzMg=="
  API_KEY: "Y2hpbm51MzE="
