apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_HOST: "MTM2LjExNS4xMzcuMTk0"   # base64 of 136.115.137.194
  DB_NAME: "cHJvZHVjdGRi"
  DB_USER: "cG9zdGdyZXM="
  DB_PASS: "cG9zdGdyZXM="
  DB_PORT: "NTQzMg=="
  API_KEY: "Y2hpbm51MzE="
