apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_HOST: "MTM2LjExMS45Ni4xOTY="   # base64 of '136.111.96.196'
  DB_NAME: "cHJvZHVjdGRi"           # 'productdb'
  DB_USER: "cG9zdGdyZXM="           # 'postgres'
  DB_PASS: "cG9zdGdyZXM="           # 'postgres'
  DB_PORT: "NTQzMg=="                # '5432'
  API_KEY: "Y2hpbm51MzE="            # 'chinnu31'
