apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_HOST: "MTM2LjExNS4xMzcuMTk0"   # base64 of 136.115.137.194
  DB_NAME: "cHJvZHVjdGRi"            # base64 of 'productdb'
  DB_USER: "cG9zdGdyZXM="            # base64 of 'postgres'
  DB_PASS: "cG9zdGdyZXM="            # base64 of 'postgres'
  DB_PORT: "NTQzMg=="                # base64 of '5432'
  API_KEY: "Y2hpbm51MzE="            # base64 of 'chinnu31'
