apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: gke-rest-api-pipeline
spec:
  serialPipeline:
    stages:
    - targetId: dev
      profiles: []
    - targetId: prod
      profiles: []
