apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-rest-api
  labels:
    app: gke-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-rest-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gke-rest-api
    spec:
      containers:
        - name: gke-rest-api
          image: us-central1-docker.pkg.dev/my-project-app-477009/my-artifact-repo/gke-rest-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "136.115.254.71"
            - name: DB_NAME
              value: "productdb"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "postgres"
            - name: DB_PORT
              value: "5432"
          # Readiness probe to ensure pod is ready before LB forwards traffic
          readinessProbe:
            httpGet:
              path: /products
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          # Optional liveness probe to restart unhealthy pods
          livenessProbe:
            httpGet:
              path: /products
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: gke-rest-api-service
spec:
  type: LoadBalancer
  selector:
    app: gke-rest-api
  ports:
    - protocol: TCP
      port: 80          # External port exposed
      targetPort: 8080  # Container port
