apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-rest-api
  labels:
    app: gke-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-rest-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gke-rest-api
    spec:
      containers:
        - name: gke-rest-api
          image: us-central1-docker.pkg.dev/my-project-app-477009/my-artifact-repo/gke-rest-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # TEMP DEBUG: override DB settings to avoid startup crash
          env:
            - name: DB_HOST
              value: "127.0.0.1"   # local unreachable DB so app doesn't crash immediately
            - name: DB_NAME
              value: "debugdb"
            - name: DB_USER
              value: "debug"
            - name: DB_PASS
              value: "debug"
            - name: DB_PORT
              value: "5432"
          # Optional: temporary sleep to keep container alive for testing
          command: ["sh", "-c", "echo 'Starting debug container'; sleep 3600"]

---
apiVersion: v1
kind: Service
metadata:
  name: gke-rest-api-service
spec:
  type: LoadBalancer
  selector:
    app: gke-rest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080


