apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-rest-api
  labels:
    app: gke-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-rest-api
  template:
    metadata:
      labels:
        app: gke-rest-api
    spec:
      # If using a docker registry secret, uncomment the line below and create the secret
      # imagePullSecrets:
      # - name: regcred
      containers:
        - name: gke-rest-api
          # Replace this with a working image URL (Artifact Registry path or public registry)
          image: us-central1-docker.pkg.dev/my-project-app-477009/product-repo/gke-rest-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "136.115.254.71"
            - name: DB_NAME
              value: "productdb"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "postgres"
            - name: DB_PORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: gke-rest-api-service
spec:
  type: LoadBalancer
  selector:
    app: gke-rest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
