apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-rest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gke-rest-api
  template:
    metadata:
      labels:
        app: gke-rest-api
    spec:
      containers:
      - name: gke-rest-api
        image: gcr.io/YOUR_PROJECT_ID/gke-rest-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: 35.194.2.254
        - name: DB_NAME
          value: productdb
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASS
        - name: DB_PORT
          value: "5432"
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
        command:
          - /cloud_sql_proxy
          - -instances=YOUR_PROJECT_ID:YOUR_REGION:YOUR_INSTANCE_NAME=tcp:5432
          - -credential_file=/secrets/cloudsql/credentials.json
        volumeMounts:
        - name: cloudsql-instance-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: gke-rest-api-service
spec:
  type: LoadBalancer
  selector:
    app: gke-rest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
