apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-workload-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: product-api-gsa@my-project-app-477009.iam.gserviceaccount.com

    


