# gke-rest-api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gke-rest-api-service
spec:
  selector:
    app: gke-rest-api   # make sure this matches your deployment's label
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # external port
      targetPort: 8080  # container port
