apiVersion: v1
kind: Service
metadata:
  name: gke-rest-api-service
  annotations:
    cloud.google.com/backend-config: '{"default": "api-backendconfig"}'
    cloud.google.com/neg: '{"ingress": false}'
spec:
  type: LoadBalancer
  selector:
    app: gke-rest-api
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
